### ISSUE TITLE
text and date field?

### ISSUE THREAD

**Issue by Mustyy** [AdrienGuille/pyMABED#2]
Hey Adrien
Thanks for your help on the previous issue

I saved my data as a csv file with a field named text containing the tweets and a field named date
When I run: python3 detect_events.py newtweets.csv 10

I get the error 

File "/Users/Mustafa/Desktop/pyMABED/mabed/corpus.py", line 37, in __init__
    text_column_index = header.index('text')
ValueError: 'text' is not in list

**Comment by Mustyy** [comment]
now its just throwing this error

Traceback (most recent call last):
  File "detect_events.py", line 35, in <module>
    my_corpus = Corpus(args.i, args.sw, args.maf, args.mrf)
  File "/Users/Mustafa/Desktop/pyMABED/mabed/corpus.py", line 36, in __init__
    header = next(csv_reader)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3809: invalid start byte

**Comment by AdrienGuille** [comment]
Hi Mustyy,

It seems that your csv file contains non utf-8 characters. I think you need to preprocess it before passing it to pyMABED.

Adrien
